module JsonContracts {
    export interface ACCOUNT_BALANCE {
        user: string,
        agentName: string,
        boothAddress: string,

        accountNumber: string,
        customerId: string,
        accountType: string,

        accountName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        customerAddress: string,
        customerName: string,
        mobileNo: string,
        printDate: string,
        requestId: string,
        transactionCode: string,
        transactionDate: string,
        photo: string
    };
    export interface ATM_DEBIT_CARD_CANCEL {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface ATM_DEBIT_CARD_DELIVERY {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface ATM_DEBIT_CARD_REQUEST {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface CASH_DEPOSIT {
        user: string,
        agentName: string,
        boothAddress: string,

        accountNumber: string,
        customerId: string,
        accountType: string,

        accountName: string,
        customerAddress: string,
        mobileNo: string,


        depositAmount: string,
        inWords: string,
        chargeAndVat: string;
        depositDate: string,
        transactionCode: string,
        printDate: string,

        requestId: string,
        photo: string
    };
    export interface CASH_WITHDRAW {
        user: string,
        agentName: string,
        boothAddress: string,

        accountNumber: string,
        customerId: string,
        accountType: string,


        accountName: string,
        charge: string,
        customerAddress: string,
        customerName: string,
        mobileNo: string,
        printDate: string,
        requestId: string,
        transactionCode: string,
        transactionDate: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
        photo: string
    };
    export interface CHEQUE_BOOK_DELIVERY {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface CHEQUE_BOOK_REQUISITION {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface CHEQUE_STOP_PAYMENT_RANGE {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface CHEQUE_STOP_PAYMENT_RANGE_CANCEL {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface CHEQUE_STOP_PAYMENT_SINGLE {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface CHEQUE_STOP_PAYMENT_SINGLE_CANCEL {
        accountName: string,
        accountNumber: string,
        agentName: string,
        balanceAmount: string,
        balanceAmountInWords: string,
        boothAddress: string,
        cardBrand: string,
        cardNumber: string,
        cardType: string,
        charge: string,
        chequeAmount: string,
        chequeLeafNumber: string,
        chequeLostReason: string,
        customerAddress: string,
        customerId: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        dpsAccountType: string,
        linkAccountNumber: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        noOfLeave: string,
        photo: string,
        principalAmount: string,
        printDate: string,
        productTenor: string,
        profitRate: string,
        receiverAccountName: string,
        receiverName: string,
        requestId: string,
        retrieveFrom: string,
        savingsAccountType: string,
        statement: Array<Array<any>>
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        userId: string,
        withdrawAmount: string,
        withdrawsAmountInWords: string,
    };
    export interface DPS_ACCOUNT {
        user: string,
        agentName: string,
        boothAddress: string,

        customerId: string,
        accountType: string,
        linkAccountNumber: string,

        accountName: string,
        customerAddress: string,
        customerName: string,
        depositAmount: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        printDate: string,
        productTenor: string,
        requestId: string,
        transactionDate: string,
        photo: string
    };
    export interface FIXED_DEPOSIT {
        user: string,
        agentName: string,
        boothAddress: string,

        customerId: string,
        accountType: string,
        linkAccountNumber: string,

        accountName: string,
        customerAddress: string,
        customerName: string,
        depositAmount: string,
        maturityAmount: string,
        maturityDate: string,
        mobileNo: string,
        printDate: string,
        principalAmount: string,
        profitRate: string,
        productTenor: string,
        requestId: string,
        transactionDate: string,
        photo: string
    };
    export interface FUND_TRANSFER {
        user: string,
        agentName: string,
        boothAddress: string,

        senderAccountNumber: string,
        customerId: string,
        accountType: string,

        accountName: string,
        customerAddress: string,
        customerName: string,
        depositAmount: string,
        depositAmountInWords: string,
        linkAccountNumber: string,
        maturityDate: string,
        mobileNo: string,
        printDate: string,
        receiverAccountName: string,
        requestId: string,
        termDepositAccountType: string,
        transactionCode: string,
        transactionDate: string,
        photo: string
    };
    export interface MINI_STATEMENT {
        user: string,
        agentName: string,
        boothAddress: string,

        accountNumber: string,
        customerId: string,
        accountType: string,
        transactionCode: string,

        customerAddress: string,
        accountName: string,
        depositAmount: string,
        mobileNo: string,
        printDate: string,
        requestId: string,
        statement: Array<Array<string>>
        photo: string
    };
    export interface REMITTANCE_DISBURSEMENT {
        user: string,
        agentName: string,
        boothAddress: string,

        recipientName: string,
        exchangeHouse: string,
        pin: string,

        mobileNo: string,

        senderName: string,
        senderCountry: string,
        actualPayableAmount: string,
        amountInWords: string,

        idType: string,
        idNumber: string,
        printDate: string,

        photo: string,
        requestId: string
    };
    export interface REMITTANCE_REQUEST {
        user: string,
        agentName: string,
        boothAddress: string,

        recipientName: string,
        pin: string,

        mobileNo: string,

        senderName: string,
        senderCountry: string,
        actualPayableAmount: string,
        amountInWords: string,

        idType: string,
        idNumber: string,
        printDate: string,

        photo: string,
        requestId: string
    };
    export interface SAVINGS_ACCOUNT {
        user: string,
        agentName: string,
        boothAddress: string,

        accountNumber: string,
        customerId: string,
        accountType: string,

        accountName: string,
        customerAddress: string,
        customerName: string,
        depositAmount: string,
        mobileNo: string,
        printDate: string,
        requestId: string,
        transactionDate: string,
        photo: string
    };
}