namespace ReceiptTypeModule {
    export enum Receipts {
        ACCOUNT_BALANCE = 1,
        CASH_DEPOSIT = 2,
        CASH_WITHDRAW = 3,
        DPS_ACCOUNT = 4,
        FIXED_DEPOSIT = 5,
        FUND_TRANSFER = 6,
        SAVINGS_ACCOUNT = 7,
        ATM_DEBIT_CARD_REQUEST = 8,
        ATM_DEBIT_CARD_DELIVERY = 9,
        ATM_DEBIT_CARD_CANCEL = 10,
        CHEQUE_BOOK_REQUISITION = 11,
        CHEQUE_BOOK_DELIVERY = 12,
        CHEQUE_STOP_PAYMENT_SINGLE = 13,
        CHEQUE_STOP_PAYMENT_RANGE = 14,
        CHEQUE_STOP_PAYMENT_SINGLE_CANCEL = 15,
        CHEQUE_STOP_PAYMENT_RANGE_CANCEL = 16,
        MINI_STATEMENT = 17,
        REMITTANCE_REQUEST = 18,
        REMITTANCE_DISBURSEMENT = 19
    };
}