module ReceiptTypeModule {
    export enum Receipts {
        ACCOUNT_BALANCE = 1,
        CASH_DEPOSIT,
        CASH_WITHDRAW,
        DPS_ACCOUNT,
        FIXED_DEPOSIT,
        FUND_TRANSFER,
        SAVINGS_ACCOUNT,
        ATM_DEBIT_CARD_REQUEST,
        ATM_DEBIT_CARD_DELIVERY,
        ATM_DEBIT_CARD_CANCEL,
        CHEQUE_BOOK_REQUISITION,
        CHEQUE_BOOK_DELIVERY,
        CHEQUE_STOP_PAYMENT_SINGLE,
        CHEQUE_STOP_PAYMENT_RANGE,
        CHEQUE_STOP_PAYMENT_SINGLE_CANCEL,
        CHEQUE_STOP_PAYMENT_RANGE_CANCEL,
        MINI_STATEMENT,
        REMITTANCE_REQUEST,
        REMITTANCE_DISBURSEMENT
    };
}